language: python
services:
  - rabbitmq
jobs:
  include:
    - stage: lint
      python: "3.7-dev"
      install:
        - pip install -e .[dev]
      script: pylint aiomessaging
    - script: mypy aiomessaging --ignore-missing-imports
    - stage: test
      python:
        - "3.6"
        - "3.7-dev"
      install:
        - pip install -e .[dev]
        - pip install codecov
      after_success:
        - codecov
      script:
        - pytest --cov-report=term-missing --cov aiomessaging
