language: python
python:
  - "3.6"
  - "3.7-dev"
services:
  - rabbitmq
jobs:
  include:
    - stage: lint
      python: "3.7-dev"
      install:
        - pip install -e .[dev]
      script:
        - pylint aiomessaging
        - mypy aiomessaging --ignore-missing-imports
    - stage: test
      install:
        - pip install -e .[dev]
        - pip install codecov
      after_success:
        - codecov
      script:
        - pytest --cov-report=term-missing --cov aiomessaging
