language: python
python:
  - "3.6"
  - "3.7-dev"
services:
  - rabbitmq
install:
  - pip install -e .[dev]
  - pip install codecov
script:
  - pytest --cov-report=term-missing --cov aiomessaging
  - mypy aiomessaging --ignore-missing-imports
  - pylint aiomessaging
after_success:
  - codecov
jobs:
  include:
    - stage: lint
      python: "3.7-dev"
      script:
        - pylint aiomessaging
        - mypy aiomessaging --ignore-missing-imports
    - stage: test
      script:
        - pytest --cov-report=term-missing --cov aiomessaging
