language: python
python:
  - "3.6"
  - "3.7-dev"
services:
  - rabbitmq
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run pytest --cov-report=term-missing --cov aiomessaging
  - pipenv run mypy aiomessaging --ignore-missing-imports
after_success:
  - codecov
