language: python
python:
  - "3.6"
  - "3.7-dev"
services:
  - rabbitmq
install:
  - pip install -r requirements-dev.txt
script:
  - pytest --cov-report=term-missing --cov aiomessaging
after_success:
  - codecov
