language: python
jobs:
  include:
    - stage: lint
      sudo: true
      dist: xenial
      python: "3.7"
      install:
        - pip install -e .[dev]
      script: pylint aiomessaging
    - python: "3.7"
      sudo: true
      dist: xenial
      install:
        - pip install -e .[dev]
      script: mypy aiomessaging --ignore-missing-imports
    - stage: test
      services:
        - rabbitmq
      python: "3.6"
      install:
        - pip install -e .[dev]
        - pip install codecov
      script:
        - pytest --cov-report=term-missing --cov aiomessaging
    - services:
        - rabbitmq
      sudo: true
      dist: xenial
      python: "3.7"
      install:
        - pip install -e .[dev]
        - pip install codecov
      after_success:
        - codecov
      script:
        - pytest --cov-report=term-missing --cov aiomessaging
